<a href="https://colab.research.google.com/github/AISHIK1/NN-with-Pytorch/blob/main/pytorch_custom_foward_backward_pass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

os.environ['KAGGLE_USERNAME'] = 'aishik996'
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_61236d6a08ac73ba31896583260ad688'

In [ ]:
!kaggle datasets download -d uciml/breast-cancer-wisconsin-data

Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
Downloading breast-cancer-wisconsin-data.zip to /content
100% 48.6k/48.6k [00:00<00:00, 950kB/s]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [ ]:
import zipfile

with zipfile.ZipFile('breast-cancer-wisconsin-data.zip', 'r') as zip_ref:
    zip_ref.extractall()

In [ ]:
df=pd.read_csv('data.csv')

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [ ]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
le=LabelEncoder()

y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [ ]:
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

In [ ]:
X_train.shape

torch.Size([455, 30])

In [ ]:
class MyNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y=torch.sigmoid(z)
    return y

  def loss(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

In [ ]:
learning_rate=0.1
epochs=25

In [ ]:
model=MyNN(X_train)
model.weights

for i in range(epochs):
  y_pred=model.forward(X_train)
  loss=model.loss(y_pred,y_train)

  #print(f'Epoch : {i+1},loss : {loss}/n')

  #backwards progogation

  loss.backward()

  #now parameteres update with gradient tracking off
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #setting the weights to zero

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch : {i+1},loss : {loss}')

Epoch : 1,loss : 3.171054343325477
Epoch : 2,loss : 3.031440772466052
Epoch : 3,loss : 2.886735890471526
Epoch : 4,loss : 2.7405924813480946
Epoch : 5,loss : 2.588468426186939
Epoch : 6,loss : 2.433715212287063
Epoch : 7,loss : 2.2775646223824326
Epoch : 8,loss : 2.123757401499622
Epoch : 9,loss : 1.9748706266031635
Epoch : 10,loss : 1.8292800756446117
Epoch : 11,loss : 1.687489654892436
Epoch : 12,loss : 1.5519263089901365
Epoch : 13,loss : 1.4245785038367085
Epoch : 14,loss : 1.3087923353609476
Epoch : 15,loss : 1.2081511679197998
Epoch : 16,loss : 1.1229990843081583
Epoch : 17,loss : 1.0529174962644174
Epoch : 18,loss : 0.9966156143004723
Epoch : 19,loss : 0.9520671625052913
Epoch : 20,loss : 0.9169182341273715
Epoch : 21,loss : 0.8889327441307057
Epoch : 22,loss : 0.8662518068852413
Epoch : 23,loss : 0.8474529180680718
Epoch : 24,loss : 0.8315020767524005
Epoch : 25,loss : 0.8176731345605033

In [ ]:
#evaluation

with torch.no_grad():
  y_pred=model.forward(X_test)
  y_pred=(y_pred>0.9).float()

  accuracy=(y_pred==y_test).float().mean()
  print(f'Accuracy : {accuracy}')

Accuracy : 0.6120344996452332